version: '3.8'

services:
  web:
    build: .
    container_name: flask_server
    command: python main.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: pg_database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_data: